name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: docker build -t ml_model .
      - run: docker tag ml_model xcosmicotter/mlops_tp1
      - run: docker login -u "${{secrets.SECRET_MLOPS_TP1}}"  --password-stdin"
      - run: docker push xcosmicotter/mlops_tp1    
      - run: ssh ubuntu@17.2.2.1 "docker compose pull xcosmicotter/mlops_tp1"
      - run: "(re)start container"

