name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - use: action/checkout 
      - run: docker compose build ml_model
      - run: docker tag ml_model xcosmicotter/mlops_tp1
      - run: docker login -p ${{SECRET_MLOPS_TP1}}
      - run: docker push xcosmicotter/mlops_tp1    
      - run: ssh ubuntu@17.2.2.1 "docker compose pull xcosmicotter/mlops_tp1"
      - run: "(re)start container"

